[project]
name = "trading-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "logfire>=3.16.0",
    "matplotlib>=3.10.3",
    "notebook>=7.4.2",
]
